[package]
name = "uvm_jni"
version = "0.1.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
jni = "0.14.0"
uvm_core = "0.6.1"
error-chain = "0.12.0"
log = "0.4.8"
flexi_logger = "0.14.4"

[lib]
crate-type = ["cdylib"]
