[package]
name = "uvm_jni"
version = "0.1.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
jni = "0.13.0"
uvm_core = "0.3.1"
error-chain = "0.12.0"
log = "0.4.7"
flexi_logger = "0.13.2"

[lib]
crate-type = ["cdylib"]
