[package]
name = "uvm_jni"
version = "0.2.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"

[dependencies]
jni = "0.14.0"
uvm-install2 = "0.3.3"
error-chain = "0.12.0"
log = "0.4.8"
flexi_logger = "0.14.4"

[lib]
crate-type = ["cdylib"]
