[package]
name = "uvm_jni"
version = "0.2.1"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"

[dependencies]
jni = "0.15.0"
uvm-install2 = "0.9.2"
uvm_core = "0.13.2"
log = "0.4.8"
flexi_logger = "0.15.1"
thiserror = "1.0.37"

[lib]
crate-type = ["cdylib"]
