[package]
name = "uvm_jni"
version = "0.2.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]
edition = "2018"

[dependencies]
jni = "0.15.0"
uvm-install2 = "0.4.1"
error-chain = "0.12.4"
log = "0.4.8"
flexi_logger = "0.15.1"

[lib]
crate-type = ["cdylib"]
