version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/rust"
    update_schedule: "live"
  - package_manager: "java:gradle"
    directory: "/rust"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"